name: flexible_text
description: Powerful and flexible solution to create dynamic, interactive and customizable text with widgets, allows to write a single text block to show anything you want.
version: 0.0.0
homepage: https://github.com/rkishan516/flexible_text
repository: https://github.com/rkishan516/flexible_text
topics: [widgets, flexible, text, styling, rich]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
